trigger:
- '*'

- job: TestHostedAgent
  pool:
    name: 'Azure Pipelines'
    demands:
      - ImageVersion -equals ubuntu-20.04
  steps:
    - script: echo "Running on Microsoft-hosted Ubuntu agent"
